// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package registry

import (
	"github.com/study/go-study/clean-architecture/infra/client"
	"github.com/study/go-study/clean-architecture/interface/controller"
	"github.com/study/go-study/clean-architecture/interface/presenter"
	"github.com/study/go-study/clean-architecture/usecase"
)

// Injectors from wire.go:

func InitAddress() *controller.AddressController {
	addressPresenter := presenter.NewAddressPresenter()
	zipCloudImplement := client.NewZipCloudImplement()
	addressInteractor := usecase.NewAddressInteractor(addressPresenter, zipCloudImplement)
	addressController := controller.NewAddressController(addressInteractor)
	return addressController
}
